name: oppgave 16
on:
  push:
    paths:
      - .github/workflows/oppgave16.yml
  workflow_dispatch: 

jobs:
  job1:
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Blackjack script file
        run: ./src/oppgave_10a.ps1

      - creds: ${{ secrets.AZURE_CRDENTIALS }} 

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CRDENTIALS }} 
          enable-AzPSSession: true